var __TWCNL = {
  // MOD_ID
  MOD_ID: 'TWCNClickerCNT',

  // Number ending
  NUM_COOKIES: '塊餅乾',

  // Big number
  CN_UNITS: [
    [1e72, '大數'],
    [1e68, '無量'],
    [1e64, '不可思議'],
    [1e60, '那由他'],
    [1e56, '阿僧祇'],
    [1e52, '恆河沙'],
    [1e48, '極'],
    [1e44, '載'],
    [1e40, '正'],
    [1e36, '澗'],
    [1e32, '溝'],
    [1e28, '穰'],
    [1e24, '秭'],
    [1e20, '垓'],
    [1e16, '京'],
    [1e12, '兆'],
  ],

  // Stackable units
  CN_UNITS_STACKABLE: [
    [1e8, '億'],
    [1e4, '萬'],
    [1e3, '千'],
    [1e2, '百'],
    [1e1, '十'],
  ],

  // Min unit display value
  CN_UNITS_MIN: ['十', '百', '千', '萬', '億'],

  // Custom building actions
  STR_BUILDING_ACTION_REGEX: /到目前爲止生產出 <b>(.*) 塊餅乾<\/b>/,
  CN_BUILDING_ACTION: {
    'clicked': '到目前爲止點擊了 [X] 次餅乾',
    'baked': '到目前爲止烘焙了 [X] 塊餅乾',
    'harvested': '到目前爲止收穫了 [X] 塊餅乾',
    'mined': '到目前爲止開採出了 [X] 塊餅乾',
    'mass-produced': '到目前爲止量產了 [X] 塊餅乾',
    'banked': '到目前爲止投資獲得了 [X] 塊餅乾',
    'discovered': '到目前爲止發現了 [X] 塊餅乾',
    'summoned': '到目前爲止召喚了 [X] 塊餅乾',
    'shipped': '到目前爲止運輸了 [X] 塊餅乾',
    'transmuted': '到目前爲止冶煉出了 [X] 塊餅乾',
    'retrieved': '到目前爲止獲取了 [X] 塊餅乾',
    'recovered': '到目前爲止回收了 [X] 塊餅乾',
    'condensed': '到目前爲止聚合了 [X] 塊餅乾',
    'converted': '到目前爲止轉化出了 [X] 塊餅乾',
    'spontaneously generated': '到目前爲止隨機出現了 [X] 塊餅乾',
    'made from cookies': '到目前爲止有 [X] 塊餅乾雙倍分形了',
    'programmed': '到目前爲止計算出了 [X] 塊餅乾',
    'hijacked': '到目前爲止劫持了 [X] 塊餅乾',
    'imagined': '到目前爲止想像出了 [X] 塊餅乾',
  },

  // Custom building level tooltips
  STR_BUILDING_EXTRANAME_REGEX: /获得<b>/,
  CN_BUILDING_EXTRANAME: {
    '[X] extra finger': '[X] 只額外手指爲你',
    'Grandmas are [X] year older': '奶奶們又老了 [X] 歲，她們的經驗爲你',
    '[X] more acre': '[X] 英畝的擴充地爲你',
    '[X] mile deeper': '所有礦坑都加深了 [X] 英里，爲你',
    '[X] additional patent': '[X] 項新專利爲你',
    'Interest rates [X]% better': '銀行的利率提高了 [X]%，爲你',
    '[X] sacred artifact retrieved': '發現了 [X] 處神聖的遺蹟，爲你',
    'Incantations have [X] more syllable': '每個咒語都添加了 [X] 個新音節，爲你',
    '[X] galaxy fully explored': '完全探索了 [X] 個銀河，爲你',
    '[X] primordial element mastered': '掌握了 [X] 個基原元素，爲你',
    '[X] dimension enslaved': '統治了 [X] 個超元維度，爲你',
    '[X] century secured': '收復了 [X] 個世紀，爲你',
    '[X] extra quark flavor': '有 [X] 種新的夸克風味爲你',
    '[X] new color discovered': '發現了 [X] 種新的顏色，爲你',
    'Chancemakers are powered by [X]-leaf clovers': '機會製造機由[X]葉幸運草驅動，爲你',
    '[X] iteration deep': '經過 [X] 層迭代，你',
    'Equipped with [X] external library': '接入了 [X] 個第三方庫，爲你',
    '[X] manifold': '[X] 個宇宙合集爲你',
    '[X] extra IQ point': '[X] 點額外的IQ點數，爲你',
  },

  // Default settings
  DEF_SETTING_TRILLION: 1,
  DEF_SETTING_BRAND: 0,

  // Strings
  STR_PURCHASE: '購買',
  STR_PURRCHASE: '收養',
  STR_INFINITY: '無限',
  STR_SETTING_TITLE: '中文模組設置',
  STR_SETTING_CNUNIT: '使用中文計數單位',
  STR_SETTING_CNUNIT_LABEL: '按住<b>Z鍵</b>可臨時顯示完整數字',
  STR_SETTING_DECIMAL: '中文單位前保留',
  STR_SETTING_DECIMAL_RIGHT: '小數點後[$]位',
  STR_SETTING_MIN_UNIT: '最小計數單位',
  STR_SETTING_TRILLION: '啓用“兆”單位',
  STR_SETTING_TRILLION_LABEL: '啓用後 <b>1萬億</b> 將顯示爲 <b>1兆</b>',
  STR_SETTING_SCIENTIFIC: '使用科學計數法',
  STR_SETTING_SCIENTIFIC_LABEL: '替換完整數字爲優化版的科學計數法，禁用後使用原版數字顯示',
  STR_SETTING_SCILEN: '數字長度',
  STR_SETTING_SCILEN_VALUES: ['完整', '長', '中', '短'],
  STR_SETTING_SCILEN_LABEL: '可以調整數字顯示的長度，普通數字和科學計數法均會被影響',
  STR_SETTING_FIXLEN: '固定小數位數',
  STR_SETTING_FIXLEN_LABEL: '啓用後中文單位前的小數不會省略末尾的0',

  STR_531:
    '“從前有座山，山上有座廟，[X]在廟裏開了一家烘焙坊。一天，烘焙坊的門口傳來了敲門聲。[X]打開了門，抬頭看到了一位散發着邪惡氣息的老奶奶。老奶奶微微張口，用虛弱而詭異的聲音，開始講述她記憶中的小故事：',
  STR_534_A: '<q>可靠的小傢伙鼠不勝鼠！</q>',
  STR_534_B: '<q>可靠的小傢伙數不勝數！</q>',
  STR_606: '就像量子計算一樣，但是更有趣',
  STR_606_FUNC: code =>
    '(你買了注彩票，彩票號碼爲 ' +
    code +
    '，彩票中的獎品是' +
    choose([
      ' ' + Math.floor(Math.random() * 5 + 2) + ' 行 Javascript 代碼',
      '一次 Math.random() 的免費使用權',
      '一量子位，然而並不知道那是什麼玩意',
      '一塊被啃了一半的餅乾',
      '一臺全新的吸塵器',
      '大半杯敞口放了一天的橙子味汽水',
      '一個很好喫的三明治',
      '一大把口袋裏的碎毛',
      '某人基本乾淨的假髮',
      '免費去高檔餐廳參觀的機會',
      '一張寫着 ' + code + ' 的紙',
      '一次抬頭偷看滾動新聞的機會',
      '一張半價彩票的優惠券',
      '一張自助發黴麪包的餐券',
      '永遠用不完的空氣',
      '一套' +
        choose([
          '紅色',
          '橙色',
          '黃色',
          '綠色',
          '藍色',
          '紫色',
          '黑色',
          '白色',
          '灰色',
          '棕色',
          '粉色',
          '青色',
        ]) +
        '便籤紙',
      '一次暫時提升自己智商的機會',
      '一把古老的符文劍',
      '遙遠國度的寶座',
      '黑手黨頭目的職位，祝你好運',
      '一週末的時間旅行實驗參與機會',
      '一個挺好看的小玩意',
      '與一個油井的契約',
      '一個用你自選的動物，植物和朋友做成的漢堡',
      '世界上最後一隻' + choose(['渡渡鳥', '袋狼', '獨角獸', '恐龍', '熊貓']) + '的撫養權',
      '滿滿的成就感',
      '稍縱即逝的沾沾自喜的感覺',
      '一種隱約的不安感',
      '深沉的存在恐懼',
      '延長你一週的壽命',
      '從現在開始你會有意識地自己呼吸',
      '現在可以眨眼一次',
      '和一位名人見面的機會，活人死人都可以。請在你今晚的夢裏領獎。',
      '一場很溫馨的夢',
      '一個搞怪的音效',
      '45秒不受法律約束的時間',
      '一個沒有結局的遊戲',
      '一個圓形，三角形，正方形或其他簡單的幾何形狀',
      '這條隨機出現的消息',
      '改變人生的動力',
      '無限的恐懼',
      '一個祕密的超能力',
      '下次在下次彩票開獎時中獎的機會',
      '完全不合理的彩票恐懼症',
      '一大隻蜘蛛',
      '增強你的自我價值感和決心',
      '內心的平靜',
      '一張你喜歡的網遊的兩天雙倍經驗卡',
      '一小塊宇宙，包含了你手上這張彩票的所有原子',
      '食物中毒',
      '天上的月亮！是的，月亮現在屬於你了，雖然你自己碰不到它',
      '一輛新車呦',
      '一個新的口頭禪',
      '你想要的胡思亂想',
      '……什麼鬼？刮開的區域裏什麼都沒寫',
      '最新電影的導演職位',
      '一隻很好看的小牛',
      '一枚真正的海盜金達布隆',
      '“財寶”什麼的',
      '一艘船，不過它現在在海底的某處',
      '全新的二手嬰兒鞋',
      '某個國王或王后的直系血統',
      '掌握一門已經失傳的語言的能力',
      '一首你不知道歌詞的歌曲的旋律',
      '持續的白噪聲',
      '輕度殘疾',
      '新的嘴脣',
      '一個東西',
      '一條帶有你名字的流行語',
      '一個錯字',
      '一張出獄卡',
      '你的餘生……',
      '一次禮貌的怒吼',
      '被人居高臨下地凝視一分鐘',
      '一隻被詛咒的猴爪',
      '真愛，大概',
      '一條可以自選的動物、國家、電視節目或名人的有趣事實',
      '一條流行迷因',
      '幾分鐘的樂趣',
      '空氣。其實你沒中獎，抱歉',
    ]) +
    '。)',
};
